AppVeyor: Attempted fixes
- Testing on Python2 fails because after AppVeyor has performed the clone of the repository and checkout of the commit relevant for the PR, there is no `.git` directory, and hence `git submodule update --init` fails. There's a `.gitmodules` file there describing the test_data submodule, but that's not enough apparently. Try disabling shallow cloning.

- When explicitly invoking Python3, the MinGW version appears first in the PATH; when the configure script therefore attempts to run the MSYS version, the subprocess module raises an exception:
Version 3.6, line 461, function list2cmdline()
needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'
In an attempt to mitigate this issue, simply use "python", which appears to invoke the MSYS version of Python3.